#Explicit Apriltag declaration
#IDEALLY PERCHING FROM around 8 Meters away this is when the tag detection gets really bad
#5 Meter is abit bad
#2.5 meter is no weakness
april_tags:
  [
          {id: 0,  x: 1.50000, y: 0.0000, z: 1.0, qw: 0.0, qx: 0.0, qy: -0.707, qz: 0.707},
          #{id: 1,  x: -1.5582, y: 1.0, z: 0.6, qw: 0.965, qx: 0.0, qy: -0.258819, qz: 0.0},
          #{id: 2,  x: 0.0548, y: -1.0522, z: 0.8, qw: 0.866, qx: 0.0, qy:  -0.5, qz: 0.0},
         # {id: 3,  x: -1.580, y: -2.0553, z: 0.5, qw: 0.965, qx: 0.0, qy: -0.258819, qz: 0.0},
          #{id: 4,  x: 0.0543, y: 1.0603, z: 0.5, qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0}
  ]

